Connect API
limavfabio/react-bookstore pull request #4
Opened 2022-09-22 17:17 UTC by limavfabio

This PR links the bookstore state with the API

2022-09-22 17:40 UTC, BertrandConxy requested changes
Hi @limavfabio, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 

- No linter errors
- correct flow is used
- good PR


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 17:40 UTC, BertrandConxy commented on src/redux/books/books.js
> +// import { v4 as uuidv4 } from 'uuid';
- [ ] Unnecessary commented-out codes should be removed from the codebase to make it look clean and smart. This is among the coding best practices. So please remove this line of code 😃 👍

2022-09-22 17:40 UTC, BertrandConxy commented on src/redux/books/books.js
> +  ).then((data) => data.json());
- [ ] Great job so far 👏. From the project requirements, you are expected the modern way to manage project data using different functions offered by the `redux-toolkit` like [CreateAsyncThunk](https://redux-toolkit.js.org/api/createAsyncThunk) and CreateSlice. All information about getting started and some examples can be found on the [redux-toolkit](https://redux-toolkit.js.org/introduction/getting-started) official documentation. What I would suggest is **to refactor your codes to use the method stated in the project requirements** 😃 👍

2022-09-22 17:40 UTC, BertrandConxy commented on src/redux/books/books.js
> +  await fetch(
- [ ] The same goes here and on all your action creators. Please try to use the method mentioned in the project requirements which is using CreateAsyncThunk and CreateSlice functions from the redux-toolkit library. I have added important links in the above review so, you can use them to implement it in all your action creators 😉

2022-09-23 13:41 UTC, EricMbouwe approved these changes
Hi @limavfabio, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🎉🔥
- Requested changes ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 13:43 UTC, merged